name: Build sing-box for openwrt
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      options: --rm
    env:
      TAGS: with_quic,with_gvisor,with_utls,with_clash_api,with_outbound_provider
    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache git curl go build-base

      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          repository: debiansid/sing-box
          

      - name: Get latest Go version
        id: go_version
        run: |
          GO_VERSION=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
          echo "go_version=$GO_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: Build core
        run: |
          # Fix Git ownership issue
          git config --global --add safe.directory /__w/sing-box-build/sing-box-build
          # Add remote and fetch
          git remote add sekai https://github.com/SagerNet/sing-box
          git fetch sekai
          # Get version
          VERSION=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          # openwrt build (Alpine-compatible)
          CGO_ENABLED=0 GOARCH=arm64 GOOS=linux go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" -tags "${TAGS}" -o sing-box ./cmd/sing-box

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: sing-box_core
          path: sing-box*
