name: Build sing-box for OpenWrt 

on:
  workflow_dispatch:

jobs:
  build-ipk:
    name: Build ARM64 OpenWrt IPK for Cortex-A53
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: SagerNet/sing-box
          ref: dev-next
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev rubygems build-essential binutils
          sudo gem install --no-document fpm

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}

      - name: Build sing-box for ARM64 (Cortex-A53)
        env:
          GOOS: linux
          GOARCH: arm64
          CGO_ENABLED: 0
          TAGS: with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_reality_server,with_acme,with_clash_api
        run: |
          # Target CPU: armv8-a+crypto+crc, cortex-a53+crypto+crc
          VERSION=$(go run ./cmd/internal/read_tag)
          go build -v -trimpath \
            -tags "$TAGS" \
            -ldflags "-X github.com/sagernet/sing-box/constant.Version=$VERSION -s -w -buildid=" \
            -o sing-box \
            ./cmd/sing-box

      - name: Generate shell completions
        run: |
          mkdir -p release/completions
          ./sing-box completion bash > release/completions/sing-box.bash
          ./sing-box completion fish > release/completions/sing-box.fish
          ./sing-box completion zsh > release/completions/sing-box.zsh

      - name: Create directory structure for packaging
        run: |
          mkdir -p package/usr/bin
          mkdir -p package/etc/sing-box
          mkdir -p package/etc/config
          mkdir -p package/etc/init.d
          mkdir -p package/lib/upgrade/keep.d
          mkdir -p package/usr/share/bash-completion/completions
          mkdir -p package/usr/share/fish/vendor_completions.d
          mkdir -p package/usr/share/zsh/site-functions
          mkdir -p package/usr/share/licenses/sing-box
          cp sing-box package/usr/bin/
          cp release/config/config.json package/etc/sing-box/config.json
          cp release/config/openwrt.conf package/etc/config/sing-box
          cp release/config/openwrt.init package/etc/init.d/sing-box
          cp release/config/openwrt.keep package/lib/upgrade/keep.d/sing-box
          cp release/completions/sing-box.bash package/usr/share/bash-completion/completions/sing-box.bash
          cp release/completions/sing-box.fish package/usr/share/fish/vendor_completions.d/sing-box.fish
          cp release/completions/sing-box.zsh package/usr/share/zsh/site-functions/_sing-box
          cp LICENSE package/usr/share/licenses/sing-box/LICENSE

      - name: Build Debian package with fpm
        shell: bash -e {0}
        run: |
          VERSION=$(go run ./cmd/internal/read_tag)
          fpm -s dir -t deb \
            -f \
            --name sing-box \
            --version $VERSION \
            --architecture arm64 \
            --category net \
            --license GPL-3.0-or-later \
            --description "The universal proxy platform." \
            --url "https://sing-box.sagernet.org/" \
            --maintainer "nekohasekai <contact-git@sekai.icu>" \
            --config-files /etc/config/sing-box \
            --config-files /etc/sing-box/config.json \
            --depends ca-bundle \
            --depends kmod-inet-diag \
            --depends kmod-tun \
            --depends firewall4 \
            --after-install release/config/openwrt.postinst \
            --before-remove release/config/openwrt.prerm \
            -C package \
            usr/bin/sing-box \
            etc/sing-box/config.json=/etc/sing-box/config.json \
            etc/config/sing-box=/etc/config/sing-box \
            etc/init.d/sing-box=/etc/init.d/sing-box \
            lib/upgrade/keep.d/sing-box=/lib/upgrade/keep.d/sing-box \
            usr/share/bash-completion/completions/sing-box.bash=/usr/share/bash-completion/completions/sing-box.bash \
            usr/share/fish/vendor_completions.d/sing-box.fish=/usr/share/fish/vendor_completions.d/sing-box.fish \
            usr/share/zsh/site-functions/_sing-box=/usr/share/zsh/site-functions/_sing-box \
            usr/share/licenses/sing-box/LICENSE=/usr/share/licenses/sing-box/LICENSE

      - name: Convert Debian package to IPK
        shell: bash -e {0}
        run: |
          VERSION=$(go run ./cmd/internal/read_tag)
          chmod +x .github/deb2ipk.sh
          ./.github/deb2ipk.sh arm64 sing-box_${VERSION}_arm64.deb sing-box_${VERSION}_arm64.ipk

      - name: Upload IPK artifact
        uses: actions/upload-artifact@v4
        with:
          name: sing-box-arm64-openwrt-ipk
          path: sing-box_*.ipk
