name: build sing-box windows from debiansid

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  

jobs:
  build:
    name: Debug build
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          repository:  debiansid/sing-box
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23
  build_go120:
    name: Debug build (Go 1.23)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          repository: debiansid/sing-box
          
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23
  cross:
    strategy:
      matrix:
        include:
          # windows
          - name: windows-amd64-v3
            goos: windows
            goarch: amd64
            goamd64: v3
         
          
   

      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      GOARM: ${{ matrix.goarm }}
      GOMIPS: ${{ matrix.gomips }}
      CGO_ENABLED: 1
      TAGS: with_gvisor,with_quic,with_clash_api,with_utls,with_outbound_provider
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: debiansid/sing-box
          
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23
      - name: Build
        id: build
        run: make
      - name: Test
        run: |
          echo ${{ contains(matrix.name, 'windows') }}
          echo ${{ matrix.name }}
      - name: Rename Windows
        if: ${{ contains(matrix.name, 'windows') }}
        run: mv sing-box* sing-box-${{ matrix.name }}.exe
      - name: Rename
        if: ${{ contains(matrix.name, 'linux') || contains(matrix.name, 'bsd') || contains(matrix.name, 'darwin') || contains(matrix.name, 'android') }}
        run: mv sing-box* sing-box-${{ matrix.name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: sing-box-${{ matrix.name }}
          path: sing-box*
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          tag_name: ${{ env.TAG_NAME }}
#          name: ${{ env.RELEASE_NAME }}
#          files: |
#            sing-box*
