name: Build SFA from official
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAGS: "with_gvisor,with_quic,with_utls,with_clash_api,with_conntrack"

    steps:
      - name: Checkout core Repository
        uses: actions/checkout@v4
        with:
         repository: SagerNet/sing-box
         ref: dev-next
         fetch-depth: 0

      - name: Get latest go version
        id: go_version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Checkout SFA Repository
        uses: actions/checkout@v4
        with:
          repository: SagerNet/sing-box-for-android
          path: SFA
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Build SFA
        run: |
          mkdir -p SFA/app/libs/
          make lib_install
          version=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          CGO_ENABLED=1 gomobile bind -v -androidapi 21 -javapkg=io.nekohasekai -libname=box -tags ${TAGS} -ldflags "-X github.com/sagernet/sing-box/constant.Version=${version} -buildid=" ./experimental/libbox
          cp ./libbox.aar SFA/app/libs/
          cd SFA
          echo "VERSION_NAME=${version}" > local.properties
          echo "VERSION_CODE=$(date +%Y%m%d%H)" >> local.properties
          sed -i '/signingConfigs\.release/d' app/build.gradle
          chmod +x ./gradlew
          ./gradlew assembleRelease 

      - name: Sign SFA
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
             releaseDirectory: SFA/app/build/outputs/apk/other/release
             signingKeyBase64: ${{ secrets.SIGNING_KEY }}
             alias: ${{ secrets.ALIAS }}
             keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
             keyPassword: ${{ secrets.KEY_PASSWORD }}
             
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SFA
          path: SFA/app/build/outputs/apk/other/release/*arm64-v8a-unsigned-signed.apk
