name: Build SFA

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAGS: "with_quic,with_utls,with_reality_server,with_clash_api,with_gvisor"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: PuerNya/sing-box
          ref: building

      - name: Get latest go version
        id: go_version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21.2

      - name: Checkout SFA Repository
        uses: actions/checkout@v3
        with:
          repository: SagerNet/sing-box-for-android
          path: SFA
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Build SFA
        run: |
          git remote add sekai https://github.com/SagerNet/sing-box
          git fetch sekai
          mkdir -p SFA/app/libs/
          make lib_install
          version=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          CGO_ENABLED=1 gomobile bind -v -androidapi 21 -javapkg=io.nekohasekai -libname=box -tags ${TAGS} -ldflags "-X github.com/sagernet/sing-box/constant.Version=${version} -buildid=" ./experimental/libbox
          cp ./libbox.aar SFA/app/libs/
          cd SFA
          echo "VERSION_NAME=${version}" > local.properties
          echo "VERSION_CODE=$(date +%Y%m%d%H)" >> local.properties
          sed -i '/signingConfigs\.release/d' app/build.gradle
          chmod +x ./gradlew
          ./gradlew assembleRelease
          
      - name: Sign SFA
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
             releaseDirectory: SFA/build/outputs/apk/release
             signingKeyBase64: ${{ secrets.SIGNING_KEY }}
             alias: ${{ secrets.ALIAS }}
             keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
             keyPassword: ${{ secrets.KEY_PASSWORD }}
             
      - name: split file      
        uses: jungwinter/split@v1
        with:
            msg: ${{ steps.sign_app.signedReleaseFiles }}
            separator: ':'

      - name: SFA Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Release X"
          files: |
           ${{ steps.signed_files._0 }}
           ${{ steps.signed_files._1 }}
           ${{ steps.signed_files._2 }}
           ${{ steps.signed_files._3 }}
           ${{ steps.signed_files._4 }}
      
      
