name: Build ss-rust for android

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/debug.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAGS: with_gvisor,with_quic,with_utls,with_clash_api,with_outbound_provider
      TAGS_ANDROID: with_quic,with_utls,with_clash_api,with_outbound_provider

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          repository: shadowsocks-rust
          

      - name: Install toolchain if not cross-compiling
        uses: dtolnay/rust-toolchain@stable

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          add-to-path: false
          local-cache: false

      - name: Build core
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          set -e
          CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang
          CXX=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang++
          ~/.cargo/bin/cargo build --target
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shadowsocks-rust
          path: ss*
